version: '3'

services:
  db:
    image: postgres:11-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:80
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 80:80
    depends_on:
      - db

volumes:
  pgdata: