# Generated by Django 2.2.4 on 2019-08-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aigo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aigo',
            options={'managed': False},
        ),
    ]
