# Generated by Django 2.2.4 on 2019-08-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aigo', '0002_auto_20190812_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aigo',
            options={},
        ),
    ]
