# Generated by Django 2.2.4 on 2019-08-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aigo', '0003_auto_20190812_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aigo',
            name='date',
        ),
    ]
